#ifndef __EXTRA_HAL_CONF_H
#define __EXTRA_HAL_CONF_H


#define HAL_RTC_MODULE_DISABLED
#define HAL_SPI_MODULE_DISABLED
//#define HAL_TIM_MODULE_DISABLED
#define HAL_DAC_MODULE_DISABLED
#define HAL_EXTI_MODULE_DISABLED
#define HAL_ETH_MODULE_DISABLED
#define HAL_SD_MODULE_DISABLED
#define HAL_QSPI_MODULE_DISABLED
#define HAL_ADC_MODULE_DISABLED
#define HAL_I2S_MODULE_DISABLED
#define HAL_SAI_MODULE_DISABLED


#define I2C_TIMING
#define SERIAL_TX_BUFFER_SIZE 256

#endif 
